{ ... }:
{
  flake.modules.nixos.nixos-containers =
    {
      config,
      lib,
      pkgs,
      options,
      ...
    }:
    {
      config = lib.mkMerge [
        {
          boot.enableContainers = true;

          networking.nat = {
            enable = true;
            internalInterfaces = [ "ve-*" ];
          };

          # Imperative containers are launched from the generic
          # container@.service template, which is DevicePolicy=closed with no
          # allowed devices. Grant /dev/net/tun so a container can create its
          # own TUN interface (e.g. for Tailscale).
          systemd.services."container@".serviceConfig.DeviceAllow = [
            "/dev/net/tun rwm"
          ];

          # nixos-container's AUTO_START=1 flag is written but never read by
          # nixpkgs, so honor it here.
          systemd.services.nixos-containers-autostart = {
            description = "Start NixOS containers flagged AUTO_START=1";
            wantedBy = [ "machines.target" ];
            before = [ "machines.target" ];
            serviceConfig = {
              Type = "oneshot";
              RemainAfterExit = true;
            };
            path = [ config.systemd.package ];
            script = ''
              set -eu

              conf_dir=/etc/nixos-containers
              [ -d "$conf_dir" ] || exit 0

              for conf in "$conf_dir"/*.conf; do
                [ -e "$conf" ] || continue

                autostart=0
                while IFS= read -r line; do
                  case "$line" in
                    AUTO_START=1) autostart=1 ;;
                  esac
                done < "$conf"
                [ "$autostart" -eq 1 ] || continue

                name="''${conf##*/}"
                name="''${name%.conf}"
                systemctl start "container@$name.service" || true
              done
            '';
          };
        }

        # Persist container roots on hosts that use impermanence. Do NOT
        # persist /etc/nixos-containers: the per-container *.conf files are
        # regenerated by environment.etc on every activation, and a
        # persistence bind-mount there would shadow them (leaving
        # container@.service without SYSTEM_PATH).
        # Use optionalAttrs (not mkIf) so the definition isn't emitted at all
        # when the option is absent; mkIf still triggers the unmatched-option
        # check. Guard on the parent option because environment.persistence is
        # an attrsOf submodule (`.main` isn't statically declared).
        (lib.optionalAttrs (options ? environment.persistence) {
          environment.persistence.main.directories = [
            "/var/lib/nixos-containers"
          ];
        })
      ];
    };
}
